trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: windows-2025

steps:
- powershell:  Write-Host Hello, world!
  displayName: 'Run a one-line script'

- powershell: wsl --list --online

- powershell: wsl --install Ubuntu-22.04 
