name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: chceck wsl version
        run: wsl --version

      - name: install wsl ubuntu
        run: wsl --install Ubuntu

      - name: list directories
        run: wsl -- ls -al

      - name: install docker
        run: wsl -- /docker-install.sh

      - name: run hello world
        run: wsl -- sudo docker run hello-world

      - name: run windows docker
        run: docker ps




        
