name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: chceck wsl version
        run: wsl --version

      - name: install wsl ubuntu
        run: wsl --install Ubuntu

      - name: install docker
        run: | 
          wsl -- sudo apt-get update
          wsl -- sudo apt-get install dos2unix
          wsl -- dos2unix ./docker-install.sh
          wsl -- ./docker-install.sh
   
      - name: compose up (wsl)
        run: |
          wsl -- sudo docker compose pull -q  
          wsl -- sudo docker compose -p test-setup up -d

      - name: docker ps (wsl)
        run: wsl -- sudo docker ps

      - name: docker ps (windows)
        run: docker ps
      
      - name: wait on db (windows)
        run: |
          $miliSeconds = 60*1000;
          $task = [System.Threading.Tasks.Task]::Delay($miliSeconds)
          $task.Wait()

      - name: run web server
        run: wsl -- sudo docker run -d -p 8080:80 --name simple-web-server nginx
          
      - name: compose logs (wsl)
        run: wsl -- sudo docker compose -p test-setup logs

      - name: curl (wsl)
        run: wsl -- curl http://localhost:8080

      - name: web-request (windows)
        run: Invoke-WebRequest -Uri http://localhost:8080

      # - name: install powershell SqlServer
      #   run: Install-Module -Name SqlServer -Scope CurrentUser -Force  

      - name: execute test query (windows)
        run: |
          Invoke-Sqlcmd `
          -ServerInstance "localhost,1433" `
          -Database master `
          -Username "sa" `
          -Password "SecretPassword9!" `
          -TrustServer `
          -Query "SELECT name FROM sys.databases" 

      - name: restore db query (windows)
        run: |
          Invoke-Sqlcmd `
          -ServerInstance "localhost,1433" `
          -Database master `
          -Username "sa" `
          -Password "SecretPassword9!" `
          -TrustServer `
          -Query "RESTORE DATABASE test FROM DISK = '/var/opt/mssql/backup/test.bak' WITH REPLACE;"

      - name: execute test query (windows)
        run: |
          Invoke-Sqlcmd `
          -ServerInstance "localhost,1433" `
          -Database test `
          -Username "sa" `
          -Password "SecretPassword9!" `
          -TrustServer `
          -Query "SELECT * FROM Person;" 




        






        
