name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: chceck wsl version
        run: wsl --version

      - name: install wsl ubuntu
        run: wsl --install Ubuntu

      - name: list directories
        run: wsl -- ls -al

      - name: list root
        run: wsl -- ls -al /

      - name: list home
        run: wsl -- ls -al /home

      - name: list mnt
        run: wsl -- ls -al /mnt

      - name: pwd
        run: wsl -- pwd

      - name: list mnt
        run: wsl -- ls -al /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/


      # - name: copy native
      #   run: |
      #     wsl -- mkdir -p ~/source
      #     wsl -- cp /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh ~/source/docker-install.sh
      #     wsl -- chmod +x ~/source/docker-install.sh

      - name: install curl
        run: |
          wsl -- sudo apt-get update
          wsl -- sudo apt-get install curl

      - name: copy native
        run: |
          wsl -- mkdir -p ~/source
          wsl -- cp /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh ~/source/docker-install.sh
          wsl -- chmod +x ~/source/docker-install.sh

      - name: install docker
        run: wsl -- bash ~/source/docker-install.sh

      # - name: install docker
      #   run: wsl -- bash /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh

      - name: run hello world
        run: wsl -- sudo docker run hello-world

      - name: run windows docker
        run: docker ps




        
