name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: chceck wsl version
        run: wsl --version

      - name: install wsl ubuntu
        run: wsl --install Ubuntu-24.04

      # - name: list directories
      #   run: wsl -- ls -al

      # - name: list root
      #   run: wsl -- ls -al /

      # - name: list home
      #   run: wsl -- ls -al /home

      # - name: list mnt
      #   run: wsl -- ls -al /mnt

      # - name: pwd
      #   run: wsl -- pwd

      # - name: list mnt
      #   run: wsl -- ls -al /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/


      # - name: copy native
      #   run: |
      #     wsl -- mkdir -p ~/source
      #     wsl -- cp /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh ~/source/docker-install.sh
      #     wsl -- chmod +x ~/source/docker-install.sh

      - name: install dos2unix
        run: |
          wsl -- sudo apt-get update
          # wsl -- sudo apt-get install curl
          wsl -- sudo apt-get install dos2unix

      - name: copy native
        run: |
          # wsl -- mkdir -p ~/source
          # wsl -- cp /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh ~/source/docker-install.sh
          # wsl -- chmod +x ~/source/docker-install.sh
          # wsl -- dos2unix ~/source/docker-install.sh
          # wsl -- dos2unix ./docker-install.sh

      - name: install docker
        run: | 
          wsl -- dos2unix ./docker-install.sh
          wsl -- ./docker-install.sh

      # - name: install docker
      #   run: wsl -- bash /mnt/d/a/ms-hosted-windows-2025/ms-hosted-windows-2025/docker-install.sh

      - name: run hello world
        run: wsl -- sudo docker run hello-world
   
      - name: run web server
        run: wsl -- sudo docker run -d -p 8080:80 --name simple-web-server nginx

      - name: logs from web server
        run: wsl -- sudo docker logs simple-web-server

      - name: curl inside wsl
        run: wsl -- curl http://localhost:8080

      - name: invoke-request powershel
        run: Invoke-WebRequest -Uri http://localhost:8080

      - name: run windows docker
        run: docker ps

      - name: run db server
        run: wsl -- sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=SecretPass94" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
      
      - name: wait for server to start
        run: |
          $miliSeconds = 60*1000;
          $task = [System.Threading.Tasks.Task]::Delay($miliSeconds)
          $task.Wait()

      - name: logs from db server
        run: wsl -- sudo docker logs sql1

      - name: install sqlcmd
        run: |
          choco install sqlcmd-tools -y
          refreshenv

      - name: verify sqlcmd
        run: sqlcmd -?

      - name: verify sqlcmd
        run: sqlcmd -S localhost,1433 -U sa -P "SecretPass94" -Q "SELECT name FROM sys.databases"



        






        
